# Generated by Django 5.2.5 on 2025-09-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("gst", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amc",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("amc_price", models.CharField(blank=True, max_length=50, null=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "domain_charges",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "server_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "server_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "maintenance_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="InProgress", max_length=50)),
            ],
        ),
    ]
