# Generated by Django 5.2.5 on 2025-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="contact",
            new_name="contact_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="client",
            name="status",
        ),
        migrations.AddField(
            model_name="client",
            name="domain_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="amc",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="amc_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="client",
            name="domain_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="maintenance_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="person_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="server_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="server_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
