# Generated by Django 5.2.5 on 2025-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='date',
            new_name='quotation_date',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
