# Generated by Django 5.2.5 on 2025-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_quotation_address_quotation_contact_quotation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
