# Generated by Django 5.2.5 on 2025-09-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0007_client_domain_end_date_client_domain_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                max_length=10,
                null=True,
            ),
        ),
    ]
