# Generated by Django 5.2.5 on 2025-09-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0008_client_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Inprogress", "Inprogress"),
                    ("Notstarted", "Notstarted"),
                    ("Completed", "Completed"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
