# Generated by Django 5.2.5 on 2025-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0009_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inprogress", "In Progress"),
                    ("Notstarted", "Not Yet Started"),
                    ("Completed", "Completed"),
                ],
                default="Notstarted",
                max_length=20,
            ),
        ),
    ]
