# Generated by Django 5.2.5 on 2025-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0010_alter_client_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inprogress", "In Progress"),
                            ("Notstarted", "Not Yet Started"),
                            ("Completed", "Completed"),
                        ],
                        default="Notstarted",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
