# Generated by Django 5.2.5 on 2025-09-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0011_enquiry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="created_at",
            new_name="date",
        ),
    ]
