# Generated by Django 5.2.5 on 2025-09-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0013_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="service_content",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="service_type",
        ),
        migrations.AddField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="crm_app.client",
            ),
            preserve_default=False,
        ),
    ]
