# Generated by Django 5.2.5 on 2025-09-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0014_remove_quotation_service_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="crm_app.client",
            ),
        ),
    ]
