# Generated by Django 5.2.5 on 2025-09-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0015_alter_quotation_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="crm_app.client",
            ),
            preserve_default=False,
        ),
    ]
