# Generated by Django 5.2.5 on 2025-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0016_alter_quotation_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Updation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("project_name", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
